# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  pytorch:
    tty: true
    image: docker.io/bitnami/pytorch:2
    volumes:
      - '.:/app'
